### ISSUE TITLE
Compiled Release?

### ISSUE THREAD

**Issue by WHiZSTA** [RMWMStevens/ScreenDimmer#2]
Can you please add a compiled release to make it easy for non-coders to use?

**Comment by RMWMStevens** [comment]
Yes of course. This was a thing mainly for personal use but I haven't had multiple monitors in a while. It has some issues but worked beautifully most of the time. 
I would recommend you to put the "ScreenDimmer.exe" in your startup folder. You can do this by pressing Ctrl+R and typing "shell:startup". Then it will start with your Windows.
You have to press LCtrl+NumDel(or Num0, don't remember) to toggle dimming on & off. 

I hope this helped :)
